import type { AuditPage, AuditResult } from "./crawl";

/**
 * Generates `llms.txt` and `llms-full.txt` from a completed audit.
 *
 * Format follows the llms.txt proposal: an H1 title, an optional `>` summary blockquote, then
 * `##` sections of `- [title](url): description` links. `llms-full.txt` is the concatenated
 * Markdown of every page — Mintlify/Anthropic's variant, which measures roughly twice the
 * crawler traffic of the index file because a model can ingest the whole site in one fetch.
 */

export interface LlmsTxtOptions {
  siteName?: string;
  summary?: string;
  /** Drop pages that scored below this — a broken page shouldn't be advertised to agents. */
  minScore?: number;
}

/** Groups by first path segment, which is how nearly every site already organizes itself. */
function sectionFor(url: string): string {
  try {
    const segments = new URL(url).pathname.split("/").filter(Boolean);
    if (segments.length === 0) return "Home";
    return titleCase(segments[0].replace(/[-_]/g, " "));
  } catch {
    return "Pages";
  }
}

function titleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

/** First real sentence of the body, used as the link description. */
function summarize(markdown: string, maxLen = 160): string {
  const body = markdown
    .split("\n")
    .filter((line) => line.trim() && !line.trim().startsWith("#"))
    .join(" ")
    .replace(/[*_`>[\]]/g, "")
    .replace(/\(https?:\/\/[^)]*\)/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (!body) return "";
  const sentenceEnd = body.indexOf(". ");
  const firstSentence = sentenceEnd > 20 && sentenceEnd < maxLen ? body.slice(0, sentenceEnd + 1) : body;
  return firstSentence.length > maxLen ? `${firstSentence.slice(0, maxLen - 1).trimEnd()}…` : firstSentence;
}

export function generateLlmsTxt(audit: AuditResult, opts: LlmsTxtOptions = {}): string {
  const minScore = opts.minScore ?? 1;
  const usable = audit.pages.filter((p) => p.ok && p.readScore >= minScore);

  const siteName = opts.siteName || deriveSiteName(audit);
  const summary =
    opts.summary ||
    `Machine-readable index of ${audit.host}. ${usable.length} page${usable.length === 1 ? "" : "s"} indexed, average AgentRead ReadScore ${audit.avgScore}/100.`;

  const lines: string[] = [`# ${siteName}`, "", `> ${summary}`, ""];

  const sections = new Map<string, AuditPage[]>();
  for (const page of usable) {
    const key = sectionFor(page.url);
    const bucket = sections.get(key);
    if (bucket) bucket.push(page);
    else sections.set(key, [page]);
  }

  // "Home" first, then everything else alphabetically — agents read top-down.
  const orderedKeys = [...sections.keys()].sort((a, b) => {
    if (a === "Home") return -1;
    if (b === "Home") return 1;
    return a.localeCompare(b);
  });

  for (const key of orderedKeys) {
    lines.push(`## ${key}`, "");
    for (const page of sections.get(key)!) {
      const description = summarize(page.markdown);
      const title = page.title?.trim() || page.url;
      lines.push(description ? `- [${title}](${page.url}): ${description}` : `- [${title}](${page.url})`);
    }
    lines.push("");
  }

  lines.push(
    "---",
    "",
    `Generated by AgentRead (https://agentread.dev) on ${new Date().toISOString().slice(0, 10)}.`,
    ""
  );

  return lines.join("\n");
}

export function generateLlmsFullTxt(audit: AuditResult, opts: LlmsTxtOptions = {}): string {
  const minScore = opts.minScore ?? 1;
  const usable = audit.pages.filter((p) => p.ok && p.readScore >= minScore && p.markdown.trim());

  const siteName = opts.siteName || deriveSiteName(audit);
  const parts: string[] = [
    `# ${siteName} — full text`,
    "",
    `> Complete Markdown corpus for ${audit.host}, ${usable.length} page${usable.length === 1 ? "" : "s"}, generated by AgentRead.`,
    "",
  ];

  for (const page of usable) {
    parts.push("---", "", `Source: ${page.url}`, "", page.markdown.trim(), "");
  }

  return parts.join("\n");
}

function deriveSiteName(audit: AuditResult): string {
  const home = audit.pages.find((p) => p.ok && p.title?.trim());
  if (home?.title) {
    // Trim the common "Page Title | Site Name" suffix down to something index-appropriate
    const parts = home.title.split(/\s[|–—-]\s/);
    if (parts.length > 1) return parts[parts.length - 1].trim();
    return home.title.trim();
  }
  return audit.host.replace(/^www\./, "");
}
